# -*- coding: utf-8 -*-
"""superstore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13y4kY28YazBmogMltwfLxqyHfjVqkkH1
"""

import pandas as pd
df = pd.read_csv("train.csv")
df.head()
df.shape
df.info()
df.describe()

import pandas as pd

df = pd.read_csv("train.csv")

# Fix date columns
df['Order Date'] = pd.to_datetime(df['Order Date'], format="%d/%m/%Y")
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format="%d/%m/%Y")

# Create new column - delivery days
df['Delivery Days'] = (df['Ship Date'] - df['Order Date']).dt.days

# Fill missing postal codes
df['Postal Code'] = df['Postal Code'].fillna(0)

print(df.shape)
print(df.isnull().sum())

from google.colab import drive
drive.mount('/content/drive')

# 1. Total sales by Category
df.groupby('Category')['Sales'].sum().sort_values(ascending=False)

# 2. Top 10 Sub-Categories by Sales
df.groupby('Sub-Category')['Sales'].sum().nlargest(10)

# 3. Which Region earns most?
df.groupby('Region')['Sales'].sum().sort_values(ascending=False)

# 4. Which Customer Segment is best?
df.groupby('Segment')['Sales'].sum()

# 5. Monthly sales trend
df['Month'] = df['Order Date'].dt.month
df['Year'] = df['Order Date'].dt.year
df.groupby(['Year','Month'])['Sales'].sum()

# 6. Which Ship Mode is most used?
df['Ship Mode'].value_counts()

# 7. Average delivery days by Ship Mode
df.groupby('Ship Mode')['Delivery Days'].mean()

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Bar chart - Sales by Category
df.groupby('Category')['Sales'].sum().plot(kind='bar', color=['#4C72B0','#DD8452','#55A868'])
plt.title("Total Sales by Category")
plt.ylabel("Sales")
plt.show()

# 2. Pie chart - Customer Segment
df.groupby('Segment')['Sales'].sum().plot(kind='pie', autopct='%1.1f%%')
plt.title("Sales by Customer Segment")
plt.show()

# 3. Line chart - Monthly Trend
monthly = df.groupby('Month')['Sales'].sum()
monthly.plot(kind='line', marker='o', color='green')
plt.title("Monthly Sales Trend")
plt.show()

# 4. Bar chart - Region wise sales
df.groupby('Region')['Sales'].sum().sort_values().plot(kind='barh')
plt.title("Sales by Region")
plt.show()

# 5. Box plot - Sales distribution by Category
sns.boxplot(x='Category', y='Sales', data=df)
plt.title("Sales Distribution by Category")
plt.show()

import pandas as pd

# Load the dataset
df = pd.read_csv("train.csv")

# Fix date columns
df['Order Date'] = pd.to_datetime(df['Order Date'], format="%d/%m/%Y")
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format="%d/%m/%Y")

# Create new column - delivery days
df['Delivery Days'] = (df['Ship Date'] - df['Order Date']).dt.days

# Fill missing postal codes
df['Postal Code'] = df['Postal Code'].fillna(0)

# Save the updated DataFrame to a new CSV file
df.to_csv('updated_train.csv', index=False)

"""The `updated_train.csv` file has been created. You can download it by clicking on the folder icon on the left sidebar (File Browser), locating `updated_train.csv`, right-clicking on it, and selecting 'Download'."""